### ISSUE TITLE
create new version of the ello.py which can speak also Dutch

### ISSUE THREAD

**Issue by mircealungu** [maravanderploeg/ParticleDetector#1]

**Comment by maravanderploeg** [comment]
I DID IT! (did you want me to change your file or create a new one by the way?)

**Comment by mircealungu** [comment]
nicely done :)

**Comment by mircealungu** [comment]
whichever you prefer :)

**Comment by mircealungu** [comment]
now, that you have fixed this issue, you can close it. 
we'll find another one for you!
