### ISSUE TITLE
present tense declination of regular verbs in Dutch

### ISSUE THREAD

**Issue by mircealungu** [maravanderploeg/ParticleDetector#5]
write a function, which, given the stem of a regular verb in Dutch, returns a list of all the present tense declinations. 

e.g. 

     present_tense("maak")
     >> maak, maakt, makat, maaken, maaken, maaken

for more info on Dutch grammar, http://www.dutchgrammar.com/en/?n=Verbs.Re07 :))

**Comment by maravanderploeg** [comment]
No complaining allowed.
